Create a Todo application
amitark7/Todo-React-Figma pull request #1
Opened 2024-04-09 13:48 UTC by amitark7

2024-04-11 05:35 UTC, amrit56789 commented on src/component/Todos.js
> +  const [todoId, setTodoId] = useState(null);
take a meaningfull variable name.

2024-04-11 05:36 UTC, amrit56789 commented on src/component/Todos.js
> +  const cancelClick = () => {
closeModal

2024-04-11 05:37 UTC, amrit56789 commented on src/component/Todos.js
> +  const saveTodoAndUpdate = () => {
addEditTodo

2024-04-11 07:27 UTC, meanstack9716 requested changes

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/TodoItem.js
> +const TodoItem = ({ todo, deleteTodo, selectTodoId, hanldeIsComplete }) => {
hanldeIsComplete typo error @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/TodoItem.js
> +            style={{ width: "15px", height: "15px" }}
remove inline styling @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +  const currentDateAndTime = moment().format("YYYY-MM-DDTHH:mm"); //this is use for input datetime minimum value
if this is for `input datetime minimum value` update the variable name accordingly @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +  const handleChange = (e) => {
handleChange => what handle change? @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +  const handleModal = () => {
which modal ?

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +  const hanldeEditAndAddTodo = () => {
typo issue @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +    const todoIndex = todoList.findIndex((todo) => todo.id === editTodoId);
you should be adding condition for editTodiId is present or not then go for todoIndex @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +    const todo = todoList.find((todo) => todo.id === editTodoId);
why can't we just pass the whole todo? which is going to edit? @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +  const selectTodoId = (id) => {
why select only id? why not full @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +    setInterval(() => {
setInterval? why @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +          onClick={handleModal}
handleModal ? @amitark7

2024-04-11 07:27 UTC, meanstack9716 commented on src/component/Todos.js
> +        <div className="absolute w-11/12 top-1/4 left-4 bg-white border-2 p-2 rounded sm:w-2/4 sm:left-40 md:w-2/5 md:left-56 lg:w-2/6 lg:left-1/3 2xl:w-1/4 2xl:left-[36rem] 2xl:top-28 2xl:p-4">
create a component for this @amitark7

2024-04-11 10:20 UTC, meanstack9716 commented on src/component/TodoItem.js
> +  changeTodoIsCompleteStatus,
change variable name.

2024-04-11 10:22 UTC, meanstack9716 commented on src/component/Todos.js
> +  const openAddUpdateModal = () => {
change openTodoPopupModal

2024-04-12 12:56 UTC, meanstack9716 commented on src/component/Todos.js
> +  const [isInvallid, setIsinValid] = useState(false);
idInvallid-> isDateValid

2024-04-12 12:56 UTC, meanstack9716 commented on src/component/Todos.js
> +  const saveUpdateAndAddTodo = () => {
saveUpdateAndAddTodo -> createOrUpdateTodo

2024-04-12 13:42 UTC, meanstack9716 commented on src/component/Todos.js
> +    time: currentTimeAndDate,
current date and time should be taken through moment

2024-04-15 07:24 UTC, merged